### ISSUE TITLE
Missing User dependency injection in app.js

### ISSUE THREAD

**Issue by prakhar1989** [EricSimons/ionic-course#5]
Hi Eric,

In the tutorial, the section where `onEnter` is defined in `splash` route, the `User` object is added like below 

``` javascript
// splash page
  .state('splash', {
    url: '/',
    templateUrl: 'templates/splash.html',
    controller: 'SplashCtrl',
    onEnter: function($state, User){
      User.checkSession().then(function(hasSession) {
        if (hasSession) $state.go('tab.discover');
      });
    }
  })
```

Running this code as it causes `checkSession()` is undefined error as the `User` service in not injected in the application (atleast the tutorial doesn't point this out).

The fix, as clear from the demo application is simple - 

``` javascript
angular.module('songhop', ['ionic', 'songhop.controllers'])
.run(function($ionicPlatform, $rootScope, $state, User) {
...
```

I would suggest updating the tutorial with this pointer as it can be stumbling block for beginners.

Thanks a ton for the great tutorial! :+1:

**Comment by EricSimons** [comment]
Gah, you're totally right! I'll fix this asap :)

**Comment by lisistrati** [comment]
i tried it but still have the Error: User.checkSession is not a function. (In 'User.checkSession()', 'User.checkSession' is undefined) ....any suggestions
