### ISSUE TITLE
Remove extra slash in Recommendations service

### ISSUE THREAD

**Issue by rvanhoepen** [EricSimons/ionic-course#6]
Hi, I'm busy with the ionic course and I'm following along with the clone of the repository. Directly after you introduced the Recommendations service you specify the $http request URL as `SERVER.url + '/recommendations'`, this causes the generated url to render with two slashes: https://ionic-songhop.herokuapp.com//recommendations and not return anything since heroku returns a 404. The server constant in app.js already has a trailing slash. That extra slash should be removed in the tutorial since it will confuse people who are following along.

So in the tutorial it should be:
```js
return $http({
     method: 'GET',
     url: SERVER.url + 'recommendations'
}).success(function(data){
     // merge data into the queue
     o.queue = o.queue.concat(data);
});
```

But its still a great tutorial and I am enjoying it so far :smiley:

**Comment by EricSimons** [comment]
Hey! This was just fixed here: https://github.com/EricSimons/ionic-course/pull/4

The issue is actually that SERVER.url shouldn't have the trailing slash - if you pull from GH, it should update for you :)
