### ISSUE TITLE
Unable to view the videos in the tutorial

### ISSUE THREAD

**Issue by neilyoung** [EricSimons/ionic-course#7]
In any browser.
https://thinkster.io/ionic-framework-tutorial/

Developer console shows this on click to start

[Error] Error: undefined is not a function (evaluating 'n.track("screencast shown",{pro:i.isPro,url:t.data.url},!0)')
showVideo@https://thinkster.io/scripts/app.js:4:11112
https://ajax.googleapis.com/ajax/libs/angularjs/1.3.11/angular.min.js:198:431
https://ajax.googleapis.com/ajax/libs/angularjs/1.3.11/angular-touch.min.js:12:198
$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.11/angular.min.js:126:193
$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.11/angular.min.js:126:424
https://ajax.googleapis.com/ajax/libs/angularjs/1.3.11/angular-touch.min.js:12:185
c@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.11/angular.min.js:32:367
	(anonyme Funktion) (angular.min.js, line 103)
	(anonyme Funktion) (angular.min.js, line 77)
	$apply (angular.min.js, line 126)
	(anonyme Funktion) (angular-touch.min.js, line 12)
	c (angular.min.js, line 32)

**Comment by emgeee** [comment]
Well that's no good, especially because I am not able to replicate it... you say it's an issue in any browser?

**Comment by neilyoung** [comment]
At least with Chrome and Safari on a Mac. But I found a hint while trying to open the video from IE10/Windows 8. "This video is available for Thinkster pro users only"

**Comment by emgeee** [comment]
The videos are only available for pro users, could that be the reason?

**Comment by neilyoung** [comment]
Yes, seems so. At least this is what the message says :)
