### ISSUE TITLE
'node build.js' error on npm install

### ISSUE THREAD

**Issue by derekriebau** [EricSimons/ionic-course#8]
very early on in the tutorial, I clone this repo, navigate to /code/, and npm install. At that point, I get this error message:

"Failed at the node-sass@0.9.6 install script 'node build.js'"

"Tell the author that this fails on your system: node build.js"

I'm not sure what went wrong at this point. I'd like to follow along with the tutorial, but I'm stuck at this point. Help?

**Comment by eithe** [comment]
Same thing here (on Windows 8). Trying to investigate.

**Comment by eithe** [comment]
Think it's related to this: https://github.com/sass/node-sass/issues/467

Might have to update packages.json (and potentially some code as well to support the new versions). This project uses quite old versions of e.g. gulp-sass

**Comment by eithe** [comment]
https://github.com/EricSimons/ionic-course/pull/9

**Comment by EricSimons** [comment]
Just merged @eithe's PR; lmk if ya'll still have problems!

**Comment by eithe** [comment]
Hi, if running on the latest versions of stuff you also need to add [cordova-plugin-whitelist](https://github.com/apache/cordova-plugin-whitelist) (`ionic plugin add cordova-plugin-whitelist`) as described in the [release log for Apache Cordova Android 4.0.0](http://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html) to be able to do ajax calls to external sites.
